#!/bin/sh
ssh -t jason@dbserver "cd /var/www/api.open.co.za/ && git pull && npm i && sudo supervisorctl restart api.open.co.za"
ssh -t jason@api-cluster-1 "cd /var/www/api.open.co.za/ && git pull && npm i && sudo supervisorctl restart api.open.co.za"
ssh -t jason@api-cluster-2 "cd /var/www/api.open.co.za/ && git pull && npm i && sudo supervisorctl restart api.open.co.za"
